version: '3.7'

networks:
  neo4j-network:

services:
  neo4j:
    restart: always
    image: bitnami/neo4j:latest
    networks:
        - neo4j-network
    environment:
        - NEO4J_AUTH=neo4j/secret
    ports:
        - "7474:7474"
        - "7687:7687"
  api:
    restart: on-failure
    build: ./
    networks:
      - neo4j-network
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    links:
      - neo4j