version: '3.7'

networks:
  neo4j-network:
    driver: bridge
    external: false
    name: neo4j-network

services:
  global_terrorism_api:
    restart: on-failure
    build: ./server
    networks:
      - neo4j-network
    container_name: global_terrorism_api
    ports:
      - 8080:8080
    environment:
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=secret
      - NEO4J_BOLT=bolt://neo4j:7687
      - SPRING_PROFILES_ACTIVE=docker
      - JVM_OPTS=-Xmx12g -Xms12g -XX:MaxPermSize=1024m
    depends_on:
      - neo4j

  global_terrorism_tracker:
    build: ./client
    container_name: global_terrorism_tracker
    networks:
      - neo4j-network
    ports:
      - 4200:4200
    depends_on:
      - global_terrorism_api

  neo4j:
    restart: always
    image: neo4j:4.1.2
    container_name: neo4j
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    networks:
      - neo4j-network
    environment:
      - NEO4J_AUTH=neo4j/secret
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    ports:
      - 7474:7474
      - 7687:7687