version: '3.7'

networks:
  neo4j-network:
    driver: bridge
    external: false
    name: neo4j-network

volumes:
    prometheus_data: {}

services:
  global_terrorism_api:
    restart: on-failure
    build: ./
    networks:
      - neo4j-network
    container_name: global_terrorism_api
    ports:
      - "8080:8080"
    environment:
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=secret
      - NEO4J_BOLT=bolt://neo4j:7687
#    volumes:
#      - ..:/global_terrorism_api
    depends_on:
      - neo4j

  prometheus:
    restart: always
    image: prom/prometheus
    user: root
    networks:
      - neo4j-network
    container_name: prometheus
    ports:
     - "9090:9090"
#    volumes:
    volumes:
      - ./src/main/resources/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
#      - ./src/main/resources/prometheus:/prometheus
#      - ./prom.yml:/prometheus/prometheus.yml
#      - ./prom.yml:/prometheus/prometheus.yml
#      - ./data/prometheus:/data
#      - ./src/main/resources/prometheus:/etc/prometheus
#      - ./src/main/resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/data'
    depends_on:
      - global_terrorism_api

  neo4j:
    restart: always
    image: neo4j:latest
    container_name: neo4j
    volumes:
        - ./conf:/conf
        - ./data:/data
        - ./import:/import
        - ./logs:/logs
        - ./plugins:/plugins
    networks:
        - neo4j-network
    environment:
        - NEO4J_AUTH=neo4j/secret
        - NEO4J_dbms_memory_pagecache_size=1G
        - NEO4J_dbms.memory.heap.initial_size=1G
        - NEO4J_dbms_memory_heap_max__size=1G
#        - NEO4J_dbms_connector_https_advertised__address="localhost:7473" -
#        - NEO4J_dbms_connector_http_advertised__address="localhost:7474"
#        - NEO4J_dbms_connector_bolt_advertised__address="localhost:7687"
    ports:
        - "7474:7474"
        - "7687:7687"