version: '3.7'

#networks:
#  neo4j-network:
#    driver: bridge
#    external: false
#    name: neo4j-network

services:
#  neo4j:
#    restart: always
#    image: bitnami/neo4j:latest
#    container_name: neo4j
#    volumes:
#        - ./conf:/conf
#        - ./data:/data
#        - ./import:/import
#        - ./logs:/logs
#        - ./plugins:/plugins
##    networks:
##        - neo4j-network
#    environment:
#        - NEO4J_AUTH=none
#        - NEO4J_dbms_memory_pagecache_size=1G
#        - NEO4J_dbms.memory.heap.initial_size=1G
#        - NEO4J_dbms_memory_heap_max__size=1G
#        - NEO4J_dbms_connector_https_advertised__address="localhost:7473" -
#        - NEO4J_dbms_connector_http_advertised__address="localhost:7474"
#        - NEO4J_dbms_connector_bolt_advertised__address="localhost:7687"
#    ports:
#        - "7473:7473"
#        - "7474:7474"
#        - "7687:7687"
  global_terrorism_api:
    restart: on-failure
    build: ./
#    networks:
#      - neo4j-network
    ports:
      - "8080:8080"
    environment:
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=secret
      - NEO4J_BOLT=bolt://192.168.99.100:7687
    volumes:
      - ..:/global_terrorism_api
#    depends_on:
#      - neo4j
#    links:
#      - neo4j