#
# Spring Data Neo4j
#
spring:
  data:
    neo4j:
      password: ${GRAPHENEDB_PASSWORD}
      uri: ${GRAPHENEDB_URL}
      username: ${GRAPHENEDB_USER}
      encryption: true

app:
  dataFilePath: data/globalterrorismdb_0919dist-heroku.xlsx