#
# Spring Data Neo4j
#
spring:
  data:
    neo4j:
      password: ${NEO4J_PASSWORD}
      uri: ${NEO4J_URL}
      username: ${NEO4J_USER}
      encryption: true
#
# Spring MVC
#
server:
  port: ${PORT:5000}
