#
# Spring Data Neo4j
#
spring:
  data:
    neo4j:
      password: ${GRAPHENEDB_PASSWORD}
#      password: ${GRAPHENEDB_BOLT_PASSWORD}
      uri: ${GRAPHENEDB_BOLT_URL}
      username: ${GRAPHENEDB_USER}
#      username: ${GRAPHENEDB_BOLT_USER}
      encryption: true
#      password: ${NEO4J_PASSWORD}
#      uri: ${NEO4J_BOLT}
#      username: ${NEO4J_USER}