#
# Spring Data Neo4j
#
spring:
  data:
    neo4j:
      password: ${GRAPHENEDB_PASSWORD}
      uri: ${GRAPHENEDB_URL}
      username: ${GRAPHENEDB_USER}
      encryption: true
      
server:
  port: ${PORT:5000}
