#
# Spring Boot
#
spring:
  profiles:
    active: docker
  bulk:
    api:
      path: /api/v1/bulk
      limit: 10
#
# Spring MVC
#
server:
  port: 8080
#
# Swagger Custom Properties
#
swagger:
  authorizationHeader: Authorization
  contactEmail: https://github.com/NowakArtur97
  contactName: Artur Nowak
  contactUrl: https://github.com/NowakArtur97
  description: REST API providing information on terrorist attacks
  license: MIT
  licenseUrl: https://github.com/NowakArtur97/GlobalTerrorismAPI/blob/master/LICENSE
  pathSelectors: /api/**
  termsOfServiceUrl: https://github.com/NowakArtur97/GlobalTerrorismAPI/blob/master/LICENSE
  title: Global Terrorism API
  version: 1.0
#
# JWT
#
jwt:
  secretKey: secret
  ignoredEndpoints: /registration,/authentication,/v2/api-docs,/configuration/ui,/swagger-resources,/configuration/security,/swagger-ui.html,/webjars
  ignoredAntMatchers: /api/v1/registration/**,/api/v1/authentication/**,/v2/api-docs,/configuration/ui,/swagger-resources/**,/configuration/security,/swagger-ui.html,/webjars/**
