#
# Neo4j Aura
#
org:
  neo4j:
    driver:
      uri: ${NEO4J_URL}
      authentication:
        username: ${NEO4J_USER}
        password: ${NEO4J_PASSWORD}
      config:
        encrypted: true
#
# Spring MVC
#
server:
  port: ${PORT:5000}
