version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:11.0.3-jdk-stretch
    - image: bitnami/neo4j:3.5.7
      environment:
        NEO4J_USER: neo4j
        NEO4J_PASSWORD: secret
        NEO4J_URL: bolt://localhost:7687/neo4j
    working_directory: ~/world_of_manga
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Neo4j
        command: docker run \ --publish=7474:7474 --publish=7687:7687 \ --volume=$HOME/neo4j/data:/data \ neo4j
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    - run: mvn test
  deploy:
    docker:
    - image: circleci/buildpack-deps:trusty
    steps:
    - checkout
    - run:
        name: Deploy app on heroku
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: deploy