package com.NowakArtur97.GlobalTerrorismAPI.enums;

public enum Region {

    NORTH_AMERICA, CENTRAL_AMERICA_AND_CARIBBEAN, SOUTH_AMERICA, EAST_ASIA, SOUTHEAST_ASIA, SOUTH_ASIA, CENTRAL_ASIA,
    WESTERN_EUROPE, EASTERN_EUROPE, MIDDLE_EAST_AND_NORTH_AFRICA, SUB_SAHARAN_AFRICA, AUSTRALASIA_AND_OCEANIA
}
